import React from 'react';
import { JournalEntry } from '@/types/tarot';
import { format } from 'date-fns';
import { TarotCardRenderer } from './TarotCardRenderer';
import { LenormandCardRenderer } from './LenormandCardRenderer';
import { MarkdownRenderer } from './MarkdownRenderer';

interface ShareableCardProps {
  entry: JournalEntry;
}

export const ShareableCard = React.forwardRef<HTMLDivElement, ShareableCardProps>(
  ({ entry }, ref) => {
    // Extract first 2-3 lines for preview
    const getPreview = (content: string, maxLines: number = 3) => {
      const lines = content.split('\n').filter(line => line.trim() !== '');
      return lines.slice(0, maxLines).join('\n');
    };

    const preview = getPreview(entry.content);

    return (
      <div
        ref={ref}
        className="w-[800px] h-[1000px] bg-white p-12 flex flex-col justify-between border-[12px] border-black relative"
        style={{ fontFamily: 'serif' }}
      >
        {/* Content */}
        <div className="relative z-10 flex flex-col h-full border-2 border-black p-8">
          {/* Header */}
          <div className="text-center mb-12 border-b-2 border-black pb-8">
            <h1 className="text-5xl font-black uppercase tracking-tighter text-black mb-2">Tarot Journal</h1>
            <p className="text-lg font-medium tracking-[0.2em] text-black/60 uppercase">Insight & Reflection</p>
          </div>

          {/* Main Content */}
          <div className="flex-1 flex flex-col space-y-12 overflow-hidden">
            {/* Tarot Cards */}
            {entry.cards && entry.cards.length > 0 && (
              <div className="flex gap-10 justify-center">
                {entry.cards
                  .filter(tag => tag.startsWith('t-') || tag.startsWith('l-'))
                  .slice(0, 3)
                  .map((cardTag, index) => {
                    const isTarot = cardTag.startsWith('t-');
                    const isLenormand = cardTag.startsWith('l-');
                    const isReverse = cardTag.includes('-reverse');
                    
                    const cleanCardName = cardTag
                      .replace('t-', '')
                      .replace('l-', '')
                      .replace('-reverse', '')
                      .trim();
                    
                    return (
                      <div key={index} className="flex flex-col items-center">
                        <div className="p-2 border border-black/20 bg-white shadow-sm">
                          {isTarot ? (
                            <TarotCardRenderer
                              cardName={cleanCardName}
                              isReverse={isReverse}
                              size="medium"
                            />
                          ) : (
                            <LenormandCardRenderer
                              cardName={cleanCardName}
                              size="medium"
                            />
                          )}
                        </div>
                        <span className="mt-2 text-xs font-bold uppercase tracking-widest text-black/40">
                          {isTarot ? (isReverse ? 'Reversed' : 'Upright') : 'Lenormand'}
                        </span>
                      </div>
                    );
                  })}
              </div>
            )}

            {/* Title and Date */}
            <div className="flex flex-col space-y-6">
              <div className="border-l-4 border-black pl-6">
                <p className="text-sm font-bold uppercase tracking-widest text-black/40 mb-1">
                  {format(new Date(entry.date), 'MMMM dd, yyyy')}
                </p>
                <h2 className="text-4xl font-black text-black leading-tight">{entry.title}</h2>
              </div>
              
              {/* Content Preview */}
              <div className="text-lg text-black/80 font-serif border-t border-black/10 pt-6">
                <MarkdownRenderer content={preview + (entry.content.split('\n').filter(l => l.trim()).length > 3 ? '...' : '')} />
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="mt-12 pt-8 border-t-2 border-black flex justify-between items-end">
            <div>
              <p className="text-xs font-bold tracking-[0.3em] uppercase text-black">Vision</p>
              <p className="text-[10px] text-black/40 uppercase">Modern Tarot Logging</p>
            </div>
            <div className="text-right">
              <p className="text-[10px] text-black/40 uppercase">Generated by</p>
              <p className="text-xs font-bold tracking-widest uppercase text-black">Tarot Journal Vision</p>
            </div>
          </div>
        </div>
      </div>
    );
  }
);

ShareableCard.displayName = 'ShareableCard';
